@DebuggingLearning.WebApi_HostAddress = http://localhost:5254

GET {{DebuggingLearning.WebApi_HostAddress}}/tasks/
Accept: application/json

###

GET {{DebuggingLearning.WebApi_HostAddress}}/tasks/cd0362ae-b716-4919-9ae1-7fd06f3302be
Accept: application/json

###

POST {{DebuggingLearning.WebApi_HostAddress}}/tasks
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "id": "cd0362ae-b716-4919-9ae1-7fd06f3302be",
  "taskType": "MemoryLeakTask",
  "status": "Processing"
}

###

DELETE {{DebuggingLearning.WebApi_HostAddress}}/tasks/cd0362ae-b716-4919-9ae1-7fd06f3302be

###

POST {{DebuggingLearning.WebApi_HostAddress}}/command
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "commandType": "GcCollect"
}

###
